package org.softRoad.security;

public enum Permission
{
    READ_USER,
    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,

    READ_ROLE,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,

    READ_AUDIT_LOG,
    CREATE_AUDIT_LOG,
    UPDATE_AUDIT_LOG,
    DELETE_AUDIT_LOG,

    READ_CATEGORY,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    DELETE_CATEGORY,

    READ_CITY,
    CREATE_CITY,
    UPDATE_CITY,
    DELETE_CITY,

    READ_COMMENT,
    CREATE_COMMENT,
    UPDATE_COMMENT,
    DELETE_COMMENT,

    READ_CONSULTANT_PROFILE,
    CREATE_CONSULTANT_PROFILE,
    UPDATE_CONSULTANT_PROFILE,
    DELETE_CONSULTANT_PROFILE,

    READ_CONSULTATION,
    CREATE_CONSULTATION,
    UPDATE_CONSULTATION,
    DELETE_CONSULTATION,

    READ_FEE,
    CREATE_FEE,
    UPDATE_FEE,
    DELETE_FEE,

    READ_PROCEDURE,
    CREATE_PROCEDURE,
    UPDATE_PROCEDURE,
    DELETE_PROCEDURE,

    READ_STEP,
    CREATE_STEP,
    UPDATE_STEP,
    DELETE_STEP,

    READ_TAG,
    CREATE_TAG,
    UPDATE_TAG,
    DELETE_TAG,

    READ_UPDATE_REQUEST,
    CREATE_UPDATE_REQUEST,
    UPDATE_UPDATE_REQUEST,
    DELETE_UPDATE_REQUEST,

    READ_USER_VERIFICATION,
    CREATE_USER_VERIFICATION,
    UPDATE_USER_VERIFICATION,
    DELETE_USER_VERIFICATION,
}
